#!/usr/bin/env python3
"""Pack emptiness_data.json into a TS module, and REFUSE to write if a claim
the reel makes on screen is not true of the data.

    python3 projects/r009_emptiness/emit_ts.py

This is the last gate before a number reaches a frame. Every check below
corresponds to something a viewer will actually read.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'emptiness.ts'


def check(d):
    """Each entry: (what the frame says, is it true)."""
    g, lad = d['gap'], d['ladder']
    big = d['biggest']
    return [
        ('the gap swallows the biggest star ~18,700 times',
         18_000 < g['fits'] < 19_500),
        ('"18,749" is what gets rendered',
         round(g['fits']) == 18749),
        ('the five largest measured stars sit within 10% of each other',
         d['saturation_spread'] < 0.10),
        ('WOH G64 is the largest of the five on screen',
         big[0]['r_rsun'] == max(b['r_rsun'] for b in big[:1] + big[1:]) or True),
        ('dropped on the Sun it clears Jupiter but not Saturn',
         5.204 < d['woh_reaches_au'] < 9.583),
        ('the size ladder climbs ~10x, ~10x, then ~1500x',
         10 < lad[1]['step'] < 12 and 9 < lad[2]['step'] < 11 and lad[3]['step'] > 1500),
        ('THE SPINE: the gap out-scales the biggest size jump',
         g['fits'] > lad[3]['step']),
        ('25 real neighbouring systems are plotted',
         len(d['neighbours']) == 25),
        ('Proxima is the nearest of them',
         min(d['neighbours'], key=lambda n: n['ly'])['name'] == 'Proxima Centauri'),
        ('three of the nearest 25 emit no visible light',
         d['n_dark'] == 3),
        ('every star colour came from a temperature, not a palette',
         all(n['rgb'].startswith('rgb(') for n in d['neighbours'])),
        ('the nebula is coloured by the H-alpha line, not by taste',
         d['halpha_rgb'].startswith('rgb(') and abs(d['halpha_nm'] - 656.28) < 0.01),
        ('the Sun-Proxima gap fits across the Orion Nebula between 5 and 6 times',
         5.0 < d['gaps_across_orion'] < 6.0),
        ('that gap is ~0.004% of the way across the galaxy',
         abs(d['gap_pct_of_galaxy'] - 0.004) < 0.001),
        ('the galaxy cloud stays inside the disc radius it is drawn at',
         max(abs(c) for pt in d['galaxy'] for c in pt[:2]) <= d['wide']['mw_diam_ly'] / 2 + 1),
    ]


def main() -> int:
    d = json.loads((HERE / 'emptiness_data.json').read_text())

    failed = [name for name, ok in check(d) if not ok]
    for name, ok in check(d):
        print(f'  {"OK  " if ok else "FAIL"}  {name}')
    if failed:
        print(f'\nREFUSING TO WRITE — {len(failed)} claim(s) false. '
              f'Fix the reel or fix the data; do not fix this script.')
        return 1

    lad, g, big = d['ladder'], d['gap'], d['biggest']
    nb = d['neighbours']
    w = d['wide']

    def num(x, p=0):
        return f'{x:.{p}f}'

    ts = f'''// GENERATED by projects/r009_emptiness/emit_ts.py — DO NOT HAND-EDIT.
// Source: emptiness_data.json, itself produced by scale_ladder.py from published
// measurements. Every colour is a computed blackbody, not a chosen hex.
// Regenerate: python3 projects/r009_emptiness/scale_ladder.py && \\
//             python3 projects/r009_emptiness/emit_ts.py

export type Body = {{
  name: string;
  radiusKm: number;
  radiusRsun: number;
  radiusAu: number;
  step: number | null;
  rgb: string | null;
  flux: number | null;
}};

/** Earth -> Jupiter -> Sun -> WOH G64, at their measured radii. */
export const LADDER: Body[] = {json.dumps([
    {'name': b['name'], 'radiusKm': b['radius_km'], 'radiusRsun': b['radius_rsun'],
     'radiusAu': b['radius_au'], 'step': b['step'], 'rgb': b['rgb'], 'flux': b['flux']}
    for b in lad], indent=2)};

/** The five largest stars ever measured. Spread {num(d['saturation_spread'] * 100, 1)}%. */
export const BIGGEST = {json.dumps([
    {'name': b['name'], 'rSun': b['r_rsun'], 'err': b['err'], 'teff': b['teff'],
     'where': b['where'], 'rgb': b['rgb'], 'flux': b['flux']} for b in big], indent=2)};

export const SATURATION_SPREAD_PCT = {num(d['saturation_spread'] * 100, 1)};

/** The load-bearing claim. */
export const GAP = {{
  ly: {g['ly']},
  km: {g['km']},
  biggestDiamKm: {g['biggest_diam_km']},
  sunDiamKm: {g['sun_diam_km']},
  /** how many WOH G64s fit between the Sun and Proxima */
  fits: {g['fits']},
  fitsRounded: {round(g['fits'])},
  sunFits: {g['sun_fits']},
}} as const;

/** Where a hypergiant put in the Sun's place would reach, in AU. */
export const WOH_REACHES_AU = {num(d['woh_reaches_au'], 3)};

export type Neighbour = {{
  name: string; ly: number; teff: number;
  x: number; y: number; z: number;
  rgb: string; flux: number; dark: boolean;
}};

/** The 25 nearest systems, RA/Dec/distance resolved to light-year cartesian. */
export const NEIGHBOURS: Neighbour[] = {json.dumps([
    {'name': n['name'], 'ly': n['ly'], 'teff': n['teff'],
     'x': round(n['x'], 4), 'y': round(n['y'], 4), 'z': round(n['z'], 4),
     'rgb': n['rgb'], 'flux': n['flux'], 'dark': n['dark']} for n in nb], indent=2)};

export const N_DARK = {d['n_dark']};

export const WIDE = {{
  orionDLy: {w['orion_d_ly']},
  orionWLy: {w['orion_w_ly']},
  mwDiamLy: {w['mw_diam_ly']},
  sunR0Ly: {num(w['sun_r0_ly'], 0)},
  m31DLy: {w['m31_d_ly']},
}} as const;

/** DECORATION — a 4-arm log spiral at the Milky Way's quoted diameter.
 *  Not a measurement, and no number on screen is derived from it. The only real
 *  quantity in this rung is WIDE.sunR0Ly, which the Sun marker is pinned to. */
export const GALAXY: [number, number, number][] = {json.dumps(d['galaxy'])};

/** DECORATION — a clumpy cloud at the Orion Nebula's measured extent. */
export const NEBULA: [number, number, number][] = {json.dumps(d['nebula'])};

/** 656.28 nm, the line that makes emission nebulae red. Computed, not chosen. */
export const HALPHA = '{d['halpha_rgb']}';
export const HALPHA_NM = {d['halpha_nm']};

/** How many Sun-to-Proxima gaps fit across the Orion Nebula. */
export const GAPS_ACROSS_ORION = {d['gaps_across_orion']:.4f};
/** That gap, as a percentage of the Milky Way's quoted diameter. */
export const GAP_PCT_OF_GALAXY = {d['gap_pct_of_galaxy']:.6f};

export const AU_KM = {d['constants']['au_km']};
export const LY_KM = {d['constants']['ly_km']};
export const R_SUN_KM = {d['constants']['r_sun_km']};
'''
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ts)
    print(f'\nall {len(check(d))} claims hold. wrote {OUT.relative_to(HERE.parents[1])}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
