#!/usr/bin/env python3
"""r017 · I86 — pack terrain.json + journey.json + plate_journey.json into a TS module, and REFUSE
to write it if any claim the reel makes on screen has stopped being true.

    python3 plate_journey.py && python3 terrain.py && python3 journey.py && python3 emit_ts.py

Beat times and copy times below MUST match remotion/src/reels/Everest.tsx. Per the r011 rule, a
claim is checked at the SCREEN SECOND its words appear, not merely somewhere in the data.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[1] / "remotion" / "src" / "reels" / "data" / "everest.ts"
TER = json.loads((HERE / "terrain.json").read_text())
JOU = json.loads((HERE / "journey.json").read_text())
PJ = json.loads((HERE / "plate_journey.json").read_text())
checks = []


def claim(text, cond):
    assert cond, f"ON-SCREEN CLAIM IS FALSE: {text}"
    checks.append(text)


# ── beats and copy times, must match Everest.tsx ─────────────────────────────────────────────
BEAT = dict(hook=(0.0, 4.5), proof=(4.5, 11.0), sea=(11.0, 17.5), race=(17.5, 25.0),
            crash=(25.0, 32.0), payoff=(32.0, 38.0), close=(38.0, 43.0))
# the race clock, piecewise linear: (screen second, millions of years ago). It slows through the
# fastest era so "FOUR TIMES FASTER" sits only on Myr where it is true (the model is >= 3.7x nails
# from 62 to 55 Ma, and 3.5x or less either side of that).
RACE_KNOTS = [(17.9, 80), (21.6, 62), (24.8, 55)]
COPY_FOUR = (21.8, 25.0)                           # "FOUR TIMES FASTER THAN YOUR FINGERNAILS GROW"
CLIMB_S = (27.0, 31.4)                             # crash beat: height readout 0 -> 29,032 FT
COPY_HIT = (25.0, 32.0)                            # "50 MILLION YEARS AGO IT HIT ASIA"


def age_at(s):
    if s <= RACE_KNOTS[0][0]:
        return RACE_KNOTS[0][1]
    for (s0, a0), (s1, a1) in zip(RACE_KNOTS[:-1], RACE_KNOTS[1:]):
        if s <= s1:
            return a0 + (a1 - a0) * (s - s0) / (s1 - s0)
    return RACE_KNOTS[-1][1]


SURVEY_FT = round(TER["survey_m"] / 0.3048)
SAMPLE_FT = round(6 / 0.3048)
NAIL = PJ["fingernail_cm_yr"]
speed = PJ["speed_cm_yr"]

# 1 · the height, the one ruler
claim('"29,032 FT" is the 2020 survey in feet', SURVEY_FT == 29032)
claim('"FIVE AND A HALF MILES" (the Gate 0 sentence) is the same height', round(PJ["everest"]["miles"], 1) == 5.5)
claim('"COLLECTED 20 FEET BELOW THE SUMMIT" is Sakai et al.\'s 6 m', SAMPLE_FT == 20)

# 2 · the amber cap is the summit limestone, and only it
H = TER["heights"]
claim("every amber terrain cell is at or above the Qomolangma detachment (8,520 m)",
      all(H[i] >= TER["detachment_m"] for i in TER["cap"]))
claim("the DEM's highest cell is amber (the summit IS the limestone)", H.index(max(H)) in set(TER["cap"]))

# 3 · the race
# every whole Myr the clock passes while the copy is up (speed[a] is the step a -> a+1 Ma)
fast = [speed[a] for a in range(int(age_at(COPY_FOUR[1])), int(age_at(COPY_FOUR[0])) + 1)]
claim(f'"FOUR TIMES FASTER THAN YOUR FINGERNAILS": India runs ≥ 3.5x nails on every Myr the copy is up '
      f'({age_at(COPY_FOUR[0]):.0f}-{age_at(COPY_FOUR[1]):.0f} Ma; min {min(fast) / NAIL:.2f}x)',
      min(fast) >= 3.5 * NAIL)
claim('"FOUR TIMES": the model peak rounds to 4x nails, and so does Cande & Stegman\'s ~18 cm/yr',
      round(PJ["peak"]["x_fingernail"]) == 4 and round(18 / NAIL) == 4)
claim("the race clock never reads less than 55 Ma — the globe never shows a contact it cannot draw",
      min(age_at(s / 10) for s in range(0, 430)) >= 55)
claim("the ocean ahead of India narrows on every Myr the race clock passes",
      all(JOU["gapKm"][a] < JOU["gapKm"][a + 1] for a in range(55, 80)))

# 4 · the crash
claim('"50 MILLION YEARS AGO IT HIT ASIA" sits inside the published onset range (59-40 Ma)', 40 <= 50 <= 59)
claim("the height readout reaches 29,032 FT before the crash beat ends", CLIMB_S[1] < BEAT["crash"][1])

# 5 · the close
claim('"ABOUT THE SPEED YOUR FINGERNAILS GROW": nails (41.6 mm/yr) lie inside GPS\'s 37-44 mm/yr',
      37 <= NAIL * 10 <= 44)

# ── write ─────────────────────────────────────────────────────────────────────────────────
quats = {pid: [v for q in qs for v in q] for pid, qs in JOU["quats"].items()}
ts = f"""// GENERATED by projects/r017_everest/emit_ts.py — never hand-edit.
// {len(checks)} on-screen claims asserted before this file was written.

export const BEAT = {json.dumps(BEAT)} as const;
export const RACE_KNOTS = {json.dumps(RACE_KNOTS)} as readonly (readonly [number, number])[];
export const COPY_FOUR = {json.dumps(COPY_FOUR)} as const;
export const CLIMB_S = {json.dumps(CLIMB_S)} as const;
export const SURVEY_FT = {SURVEY_FT};
export const SAMPLE_FT = {SAMPLE_FT};

/** Height field, metres, GRID x GRID over SPAN_KM centred on the DEM summit (AWS Terrain Tiles). */
export const TERRAIN = {{
  grid: {TER['grid']},
  spanKm: {TER['span_km']},
  demPeakM: {TER['dem_peak_m']},
  detachmentM: {TER['detachment_m']},
  heights: {json.dumps(H)} as readonly number[],
  cap: {json.dumps(TER['cap'])} as readonly number[],
}};

/** Unit quaternions (w,x,y,z), present -> t Ma, Eurasia fixed, one per whole Myr 0..{JOU['tMax']}. */
export const QUATS: Record<string, readonly number[]> = {json.dumps(quats)};
export type Outline = {{ pid: number; ll: readonly (readonly [number, number])[] }};
export const OUTLINES: readonly Outline[] = {json.dumps(JOU['outlines'])} as unknown as readonly Outline[];
export const INDIA = {json.dumps(JOU['india'])} as {{ ll: [number, number][]; tris: [number, number, number][]; ring: [number, number][] }};
export const EVEREST_LL = {json.dumps(JOU['everest'])} as [number, number];
"""
OUT.write_text(ts)
for c in checks:
    print("  ✓", c)
print(f"{len(checks)} claims hold · wrote {OUT.relative_to(HERE.parents[1])} ({OUT.stat().st_size // 1024} KB)")
