#!/usr/bin/env python3
"""Pack tides_data.json into the TS module the reel plays back.

This script REFUSES to write a module whose claims are false. Every figure the
reel puts on screen is re-checked here against the run, so a stale JSON or an
edited constant cannot reach the screen quietly.

Run:  .venv/bin/python projects/i58_tides/emit_ts.py
"""
import json
from pathlib import Path

SRC = Path(__file__).with_name('tides_data.json')
OUT = Path('remotion/src/reels/data/tides.ts')

d = json.loads(SRC.read_text())
pull, tide, bul = d['pull'], d['tide'], d['bulges']
rhy, body, env, cur = d['rhythm'], d['body'], d['envelope'], d['curve']
rat = d['ratios']

# ── the reel's claims, asserted before a single byte is written ─────────────
claims = {
    'the Sun pulls 179x harder':        round(pull['ratio']) == 179,
    'the Sun raises 0.46x the tide':    abs(tide['ratio_sun_over_moon'] - 0.46) < 0.005,
    'the Moon raises 2.2x the Sun':     abs(tide['ratio_moon_over_sun'] - 2.18) < 0.01,
    'lunar amplitude is 36 cm':         round(tide['k_moon_m'] * 100) == 36,
    'solar amplitude is 16 cm':         round(tide['k_sun_m'] * 100) == 16,
    'the far bulge is 4.9% weaker':     abs(bul['asym_pct'] - 4.9) < 0.05,
    'both residuals point outward':     bul['tide_near'] > bul['tide_far'] > 0,
    'M2 is 12h25m':                     abs(rhy['m2_h'] - 12.4206012) * 3600 < 1.0,
    'the Moon-only curve matches M2':   abs(rhy['moon_only_gap_h'] - rhy['m2_h']) * 60 < 1.0,
    'high tide is ~50 min later a day': abs(rhy['drift_min_per_day'] - 50.5) < 0.2,
    'a person at 1 m beats the Moon':   703_000 > body['person_over_moon'] > 702_000,
    'spring is 2.7x neap':              abs(tide['spring_over_neap'] - 2.70) < 0.01,
    # the reversal the whole reel rests on
    'the reversal holds':               pull['ratio'] > 100 and tide['ratio_sun_over_moon'] < 0.5,
    # the end card SHOWS a calculation; it must be the same sum that was measured
    'end-card sum gives the pull':      abs(rat['pull_from_ratios'] - pull['ratio']) < 1e-9,
    'end-card sum gives the tide':      abs(rat['tide_from_ratios'] - tide['ratio_sun_over_moon']) < 1e-12,
    'the Sun is ~389x further':         388 < rat['distance'] < 390,
    'the Sun is ~27M times heavier':    2.70e7 < rat['mass'] < 2.71e7,
    'near side is 3.4% harder':         abs(bul['near_vs_centre_pct'] - 3.4) < 0.05,
    'far side is 3.2% weaker':          abs(bul['far_vs_centre_pct'] - 3.2) < 0.05,
    'far bulge is 95 of the near':      abs(bul['bulge_far_rel'] - 95.1) < 0.1,
}
bad = [k for k, ok in claims.items() if not ok]
if bad:
    raise SystemExit('REFUSING to emit — these claims are false:\n  ' + '\n  '.join(bad))

# ── downsample for playback: the browser plays state, it does not crunch ────
STRIDE = 10                                    # 1-min samples -> 10-min samples
curve = [round(v, 5) for v in cur['moon_m'][::STRIDE]]
curve_both = [round(v, 5) for v in cur['both_m'][::STRIDE]]
envelope = [round(v, 5) for v in env['moon']]  # shape only; amplitude is applied in the reel

def arr(xs):
    return '[' + ', '.join(str(x) for x in xs) + ']'

ts = f'''// GENERATED by projects/i58_tides/emit_ts.py — do not hand-edit.
//
// r009 / I58. Every number here was produced by projects/i58_tides/tides.py from
// published constants and Newtonian gravity, and re-asserted by emit_ts.py before
// this file was written.
//
// WHAT THIS IS: the EQUILIBRIUM TIDE — the tide-raising force, not the water level
// at any real port. Real tides are set by basin resonance and lag the forcing. The
// reel says force everywhere it says anything.

export const TIDES = {{
  /** Direct gravitational pull on the Earth, m/s^2, and the Sun/Moon ratio. */
  pull: {{
    sun: {pull['sun']:.6e},
    moon: {pull['moon']:.6e},
    ratio: {pull['ratio']:.1f},
  }},
  /** Equilibrium tide amplitude K = GMR^2/(g d^3), in metres. */
  tide: {{
    moonM: {tide['k_moon_m']:.4f},
    sunM: {tide['k_sun_m']:.4f},
    moonCm: {round(tide['k_moon_m'] * 100)},
    sunCm: {round(tide['k_sun_m'] * 100)},
    sunOverMoon: {tide['ratio_sun_over_moon']:.3f},
    moonOverSun: {tide['ratio_moon_over_sun']:.3f},
    springCm: {round(tide['spring_m'] * 100)},
    neapCm: {round(tide['neap_m'] * 100)},
    springOverNeap: {tide['spring_over_neap']:.2f},
  }},
  /** Near side, centre, far side — the residuals that make two bulges. */
  bulges: {{
    aNear: {bul['a_near']:.6e},
    aCentre: {bul['a_centre']:.6e},
    aFar: {bul['a_far']:.6e},
    near: {bul['tide_near']:.6e},
    far: {bul['tide_far']:.6e},
    asymPct: {bul['asym_pct']:.1f},
    /** The same three pulls as plain relative numbers, for the screen.
     *  Scientific notation is what a script prints, not what a viewer reads. */
    nearVsCentrePct: {bul['near_vs_centre_pct']:.1f},
    farVsCentrePct: {bul['far_vs_centre_pct']:.1f},
    farBulgeRel: {bul['bulge_far_rel']:.0f},
  }},
  /** The end card, as a calculation rather than a result. The Sun is heavier
   *  AND further; dividing by the distance ratio ONE MORE TIME is the entire
   *  difference between winning the pull and losing the tide. Both lines below
   *  are asserted to reproduce the measured ratios exactly. */
  ratios: {{
    mass: {round(rat['mass']):d},
    massMillions: {rat['mass'] / 1e6:.0f},
    distance: {rat['distance']:.0f},
    pullFromRatios: {rat['pull_from_ratios']:.1f},
    tideFromRatios: {rat['tide_from_ratios']:.3f},
  }},
  rhythm: {{
    lunarDayH: {rhy['lunar_day_h']:.5f},
    m2H: {rhy['m2_h']:.7f},
    publishedM2H: {rhy['published_m2_h']},
    moonOnlyGapH: {rhy['moon_only_gap_h']:.5f},
    moonPlusSunGapH: {rhy['moon_plus_sun_gap_h']:.5f},
    sunShiftMin: {rhy['sun_shift_min']:.1f},
    driftMinPerDay: {rhy['drift_min_per_day']:.1f},
  }},
  /** The same inverse-cube law applied to a person instead of a planet. */
  body: {{
    heightM: {body['height_m']},
    massKg: {body['mass_kg']},
    moonOnBody: {body['moon_on_body']:.4e},
    personAt1m: {body['person_at_1m']:.4e},
    personOverMoon: {round(body['person_over_moon']):d},
    earthOverBody: {round(body['earth_over_body']):d},
  }},
}} as const;

/**
 * Ocean shape, as a radius multiplier at {env['step_deg']}-degree steps, relative to the
 * body's own amplitude. Moon and Sun share this shape exactly — only the
 * amplitude differs, which is the reel's whole point — so one array serves both.
 */
export const ENVELOPE_STEP_DEG = {env['step_deg']};
export const ENVELOPE: readonly number[] = {arr(envelope)};

/**
 * Equilibrium tide at a point on the equator over {int(cur['hours'])} h, in metres,
 * sampled every 10 minutes. Both bodies taken in the equatorial plane, which
 * removes the diurnal inequality and keeps the two-per-lunar-day rhythm.
 *
 * MOON_CURVE is the Moon acting alone: its highs are {rhy['moon_only_gap_h']:.3f} h apart, which
 * is the derived M2 period to under a minute. BOTH_CURVE adds the Sun, and its
 * highs come {rhy['sun_shift_min']:.1f} min EARLIER — measured, not assumed. The reel may say the
 * Moon's part repeats every 12h25m; it may not say the sea does.
 */
export const CURVE_HOURS = {cur['hours']};
export const MOON_CURVE: readonly number[] = {arr(curve)};
export const BOTH_CURVE: readonly number[] = {arr(curve_both)};
'''
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(ts)
print(f'all {len(claims)} claims verified')
print(f'envelope {len(envelope)} pts, curves {len(curve)} pts each')
print(f'wrote {OUT} ({len(ts):,} bytes)')
