"""Pack bias.py's measured run into a TS module the Remotion reel replays."""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
d = json.loads((HERE / 'bias_data.json').read_text())
j = lambda o: json.dumps(o, separators=(',', ':'))

out = f'''// GENERATED by projects/r005_shuffle/emit_ts.py — do not edit by hand.
//
// Measured output of bias.py. The per-order probabilities are EXHAUSTIVE, not
// sampled: the naive shuffle has exactly {d['paths_naive']} equally likely execution paths and
// Fisher-Yates exactly {d['paths_fy']}, so every one was enumerated. The {d['trials']:,}-run Monte
// Carlo is only there as an independent check, and it agrees to under a point.
//
// The proof the reel rests on is a counting argument, not a measurement:
// {d['paths_naive']} paths over {len(d['orders'])} orders is {d['ratio']} each, which is not a whole number, so some
// order MUST be likelier than another whatever the random source does.

export const N = {d['n']};
export const SONGS: string[] = {j(d['songs'])};
export const ORDERS: string[] = {j(d['orders'])};

export const PATHS_NAIVE = {d['paths_naive']};
export const PATHS_FY = {d['paths_fy']};
/** {d['paths_naive']} / {len(d['orders'])}. Not an integer — that IS the bug. */
export const RATIO = {d['ratio']};

/** Exact counts out of {d['paths_naive']} paths, per order. */
export const EXACT_NAIVE: number[] = {j(d['exact_naive'])};
export const PCT_NAIVE: number[] = {j(d['pct_naive'])};
/** Exact counts out of {d['paths_fy']} paths — every order exactly once. */
export const EXACT_FY: number[] = {j(d['exact_fy'])};
export const PCT_FY: number[] = {j(d['pct_fy'])};

export const PCT_HIGH = {d['pct_high']};
export const PCT_LOW = {d['pct_low']};
export const WORST_RATIO = {d['worst_ratio']};

/** A real run, replayed: cumulative counts per order at each checkpoint. */
export const TRIALS = {d['trials']};
export const CHECKPOINTS: number[] = {j(d['checkpoints'])};
export const SERIES_NAIVE: number[][] = {j(d['series_naive'])};
export const SERIES_FY: number[][] = {j(d['series_fy'])};
'''
(HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'bias.ts').write_text(out)
print('wrote remotion/src/reels/data/bias.ts')
