"""Pack heatmap.py's measured tables into a TS module the Remotion reel replays.

The reel plays the CHECKPOINT SERIES, not the final table: both grids start as
sampling noise and only one of them settles. That is the whole argument, and it
only reads if the frames come from real partial runs rather than a fade-in.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
d = json.loads((HERE / 'heatmap_data.json').read_text())
j = lambda o: json.dumps(o, separators=(',', ':'))
nv, fy = d['naive'], d['fisher_yates']

pct = lambda v: round(v * 100, 2)

out = f'''// GENERATED by projects/r005_shuffle/emit_heatmap_ts.py — do not edit by hand.
//
// Measured output of heatmap.py: over {d['runs']:,} shuffles of {d['n']} cards, how often the
// card starting at row i finished at column j. Values are normalised so 1.0 is
// exactly fair — a correct shuffle is a flat field of 1.0 and looks like nothing.
//
// Both algorithms are measured at the SAME sample size and drawn in the SAME
// colour, because the reel's claim is that the only difference is the pattern.
// The Fisher-Yates table is the honesty control: it proves "flat" is what this
// measurement produces when the shuffle is correct, so the naive staircase
// cannot be an artefact of the drawing. heatmap.py asserts it and fails rather
// than emitting a flattering picture.

export const N = {d['n']};
export const RUNS = {d['runs']};

/** Runs completed at each checkpoint — log-spaced, so noise visibly resolves. */
export const MARKS: number[] = {j(d['marks'])};

/** {len(d['marks'])} snapshots of {d['n']}x{d['n']} = {d['n'] * d['n']} cells, row-major. Replayed as the fill. */
export const SERIES_NAIVE: number[][] = {j(nv['series'])};
export const SERIES_FY: number[][] = {j(fy['series'])};

/** Mean absolute deviation from fair, in percent, at the full sample. */
export const DEV_NAIVE = {pct(nv['mean_abs_dev'])};
export const DEV_FY = {pct(fy['mean_abs_dev'])};
/** {pct(nv['mean_abs_dev'])} / {pct(fy['mean_abs_dev'])} — the bias over the noise floor. */
export const SIGNAL_NOISE = {d['signal_noise']};

/** Brightest cell over dimmest, naive. The visible contrast in the left grid. */
export const CONTRAST_NAIVE = {round(nv['contrast'], 2)};
export const LO = {round(nv['min'], 3)};
export const HI = {round(nv['max'], 3)};
'''
(HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'heatmap.ts').write_text(out)
print(f'wrote remotion/src/reels/data/heatmap.ts  ({len(out) // 1024} KB)')
