"""Pack shuffle.py's measured run into a TS module the Remotion reel replays."""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
d = json.loads((HERE / 'shuffle_data.json').read_text())
j = lambda o: json.dumps(o, separators=(',', ':'))

out = f'''// GENERATED by projects/r005_shuffle/emit_ts.py — do not edit by hand.
//
// Measured output of shuffle.py: {d['trials']:,} real Fisher-Yates shuffles of a
// {d['songs']}-song playlist, {d['artists']} artists, {d['per_artist']} songs each.
//
// The self-check is a closed form. By linearity of expectation over the n-1
// adjacent slots, E[pairs] = sum_a k_a(k_a-1)/n = {d['exact_expected_pairs']}. The Monte
// Carlo lands at {d['measured_mean_pairs']}. If those ever diverge, the shuffle is not uniform.
//
// NOT claimed anywhere in this reel: what any particular music company does with
// its shuffle. That could not be verified from here — see
// projects/r005_shuffle/NOTES.md for what was cut and how to reinstate it.

export const ARTISTS = {d['artists']};
export const PER_ARTIST = {d['per_artist']};
export const SONGS = {d['songs']};
export const TRIALS = {d['trials']};

/** Percent of uniform shuffles with >= 2 songs by one artist adjacent. Base: {d['trials']:,} shuffles. */
export const PCT_CLUMPED = {d['pct_with_any_pair']};
/** The complement — how often a shuffle comes out looking "properly shuffled". Same base. */
export const PCT_CLEAN = {round(100 - d['pct_with_any_pair'], 2)};
export const PCT_RUN_OF_3 = {d['pct_with_run_of_3']};
export const MEAN_PAIRS = {d['measured_mean_pairs']};
export const EXACT_PAIRS = {d['exact_expected_pairs']};

/** Real shuffles, replayed frame for frame. Each entry is an artist index per slot. */
export const EXAMPLES: number[][] = {j(d['examples'])};
export const EXAMPLE_PAIRS: number[] = {j(d['example_pairs'])};

/** Built to avoid repeats — 0 adjacent pairs, and far fewer permutations reachable. */
export const SPREAD: number[] = {j(d['spread'])};

export const RUN_HIST: Record<string, number> = {j(d['longest_run_hist'])};
'''

(HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'shuffle.ts').write_text(out)
print('wrote remotion/src/reels/data/shuffle.ts')
