#!/usr/bin/env python3
"""Pack divergence_data.json into a TS module, and REFUSE to write it if anything
the reel says on screen is not true of the run.

    python3 projects/r011_divergence/emit_ts.py
"""
import json
import math
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'divergence.ts'


def checks(d):
    m, f, sep = d['meta'], d['frames'], d['sepM']
    hair_m = m['hairUm'] * 1e-6
    return [
        ('the perturbation really is ONE HAIR of arc at the first bob',
         abs(sep[0] - hair_m) / hair_m < 0.02),
        ('"A HAIR\'S WIDTH" — 70 um is inside the cited 17-181 um range',
         17 <= m['hairUm'] <= 181),
        ('they start as the SAME PIXEL — under 1 px at t=0',
         sep[0] * m['pxPerM'] < 1.0),
        ('"FOR 3.3 SECONDS" is the one-pixel crossing, and rounds to 3.3',
         round(m['splitS'], 1) == 3.3),
        ('they are unmistakably two well before the copy claims it (6.2 s)',
         m['twoS'] < 6.2),
        ('they end UNRELATED, not merely offset',
         m['sepEndM'] > 0.5),
        ('NOTHING WAS RANDOM — a deterministic run conserves energy',
         m['energyDrift'] < 1e-8),
        ('the divergence is EXPONENTIAL, not linear',
         1.0 < m['lambdaPerS'] < 3.0),
        ('doubling time is under a second — the reel is built on that',
         m['doublingS'] < 1.0),
        ('every sample carries both pendulums',
         all(len(x) == 4 for x in f)),
        ('the run covers the full runtime at the stated rate',
         len(f) == int(m['runtime'] * m['hz']) + 1),
        # NOT a bound on the angles: theta winds up without limit as the arms rotate,
        # and asserting |theta| < 4*pi failed on a perfectly physical run. The real
        # geometric invariant is that the tip can never leave the arms' reach.
        ('no tip leaves the arms\' reach — the geometry is physical',
         max(math.hypot(m['l1'] * math.sin(t1) + m['l2'] * math.sin(t2),
                        -m['l1'] * math.cos(t1) - m['l2'] * math.cos(t2))
             for t1, t2, u1, u2 in f) <= m['l1'] + m['l2'] + 1e-9),
    ]


def main():
    d = json.loads((HERE / 'divergence_data.json').read_text())
    bad = [n for n, ok in checks(d) if not ok]
    for n, ok in checks(d):
        print(f"  {'ok  ' if ok else 'FAIL'} {n}")
    if bad:
        raise SystemExit(f"\nREFUSING TO WRITE — {len(bad)} claim(s) false:\n  " + "\n  ".join(bad))

    m = d['meta']
    frames = ',\n'.join('  [%s]' % ','.join(str(v) for v in fr) for fr in d['frames'])

    ts = f'''/**
 * r011 · I71 — GENERATED by projects/r011_divergence/emit_ts.py. Do not hand-edit.
 *
 * Two double pendulums released from {m['theta0Deg']} deg, one of them {m['hairUm']:.0f} um of arc
 * further along — a single human hair. Classic double-pendulum equations, RK4 at
 * dt = 1/2000 s, g = 9.80665 m/s^2. There is NO random term anywhere: the only
 * difference between the two runs is that one perturbation at t = 0.
 *
 * Energy drift {m['energyDrift']:.2e} of MgL, which is the invariant that says the
 * chaos on screen is the physics' and not the integrator's.
 *
 * Played back 1:1 — {m['runtime']} s of simulation in {m['runtime']} s of reel.
 */

export const META = {{
  theta0Deg: {m['theta0Deg']},
  /** the perturbation, in micrometres of arc at the first bob */
  hairUm: {m['hairUm']},
  l1: {m['l1']},
  l2: {m['l2']},
  runtime: {m['runtime']},
  /** samples per second in FRAMES below */
  hz: {m['hz']},
  /** the reel's own scale, and what "one pixel of daylight" is measured against */
  pxPerM: {m['pxPerM']},
  /** first sample where the tips are more than ONE SCREEN PIXEL apart */
  splitS: {m['splitS']},
  noticeS: {m['noticeS']},
  twoS: {m['twoS']},
  unrelatedS: {m['unrelatedS']},
  /** largest Lyapunov exponent, fitted on the clean growth phase */
  lambdaPerS: {m['lambdaPerS']},
  doublingS: {m['doublingS']},
}} as const;

/** [theta1_A, theta2_A, theta1_B, theta2_B] in radians, {m['hz']} Hz. */
export const FRAMES: number[][] = [
{frames},
];
'''
    OUT.write_text(ts, encoding='utf-8')
    print(f"\nwrote {OUT} ({OUT.stat().st_size/1024:.0f} KB) · {len(d['frames'])} samples")


if __name__ == '__main__':
    main()
