"""
r008 step 3 — pack the real Paris searches into a TS module for Remotion.

    python3 fetch_graph.py --bbox 48.835,2.285,48.885,2.375 --place "Central Paris" \
        --out graph_paris.json
    python3 emit_ts.py

── Why coordinates are PRE-PROJECTED here, unlike r006 ─────────────────────
r006 shipped lon/lat and projected in the .tsx, because that reel morphs between
a globe and a flat map and the projection has to be re-evaluated every frame.
This reel never morphs, and its graph is an order of magnitude bigger: 26,193
junctions against r006's 3,475 coastline points. Emitting screen integers
instead of float degrees is roughly a third of the bytes and removes per-frame
trigonometry over tens of thousands of points. The stage constants below must
therefore match Astar.tsx exactly — they are asserted there.

── What is animated ────────────────────────────────────────────────────────
Both searches are real runs of search.py, which is ONE implementation used
twice: Dijkstra is A* with h = 0. The reel replays their SETTLE ORDER, which is
the order the algorithm actually committed to each junction — not a spreading
animation invented to look like one.
"""
from __future__ import annotations

import json
import math
import pathlib

from search import build, haversine, search

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent.parent / "remotion/src/reels/data/i15_geo.ts"

# ── the stage. Must match Astar.tsx. ────────────────────────────────────────
# 700 wide, not 810, and pushed down to 640: at 810/528 the map ran under the
# step label, and 42px ash text over a bright flood is unreadable. The city is
# still the largest thing in the frame.
MAP_X, MAP_W, MAP_Y = 115, 700, 640

START = (48.8738, 2.2950)   # Arc de Triomphe
GOAL = (48.8530, 2.3499)    # Notre-Dame
CITY = "Central Paris"

graph = json.loads((HERE / "graph_paris.json").read_text())
pos, adj = build(graph)
S, W, N, E = graph["bbox"]
MAP_H = round(MAP_W * (N - S) / ((E - W) * math.cos(math.radians((N + S) / 2))))


def proj(lat, lon):
    return (
        round(MAP_X + (lon - W) / (E - W) * MAP_W),
        round(MAP_Y + (N - lat) / (N - S) * MAP_H),
    )


near = lambda ll: min(pos, key=lambda n: haversine(pos[n], ll))
s, g = near(START), near(GOAL)
gp = pos[g]
dij = search(pos, adj, s, g, lambda n: 0.0)
ast = search(pos, adj, s, g, lambda n: haversine(pos[n], gp))

# The claim on screen is "same route". Assert it rather than trusting it.
assert math.isfinite(dij["cost"]), "no route between these two points"
assert abs(dij["cost"] - ast["cost"]) < 1e-6, "A* found a different cost — heuristic inadmissible"
assert dij["path"] == ast["path"], "same cost but a different path — check tie-breaking"


def rdp(pts, eps=1.2):
    """Douglas-Peucker in SCREEN space. At 810 px for ~6.6 km one pixel is ~8 m,
    so shape points finer than a pixel cannot be seen and are pure payload."""
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    n = math.hypot(dx, dy)
    worst, wi = -1.0, 0
    for i, (x, y) in enumerate(pts[1:-1], 1):
        d = (abs(dy * x - dx * y + x2 * y1 - y2 * x1) / n) if n else math.hypot(x - x1, y - y1)
        if d > worst:
            worst, wi = d, i
    if worst <= eps:
        return [pts[0], pts[-1]]
    return rdp(pts[: wi + 1], eps)[:-1] + rdp(pts[wi:], eps)


def ordered_pixels(nodes):
    """Settle order, deduped to one entry per screen pixel. Many junctions land
    on the same pixel at this scale, and drawing a dot twice costs bytes and
    changes nothing."""
    out, seen = [], set()
    for n in nodes:
        p = proj(*pos[n])
        if p in seen:
            continue
        seen.add(p)
        out.append(p)
    return out


ways = []
for way in graph["ways"]:
    pts = [proj(*pos[n]) for n in way["nodes"] if n in pos]
    dedup = [p for i, p in enumerate(pts) if i == 0 or p != pts[i - 1]]
    if len(dedup) > 1:
        ways.append(rdp(dedup))

DIJ = ordered_pixels(dij["settled"])
AST = ordered_pixels(ast["settled"])
PATH = [proj(*pos[n]) for n in dij["path"]]

flat = lambda ps: [c for p in ps for c in p]
arr = lambda xs: "[" + ",".join(str(x) for x in xs) + "]"

ts = f'''// GENERATED by projects/i15_astar/emit_ts.py — do not edit by hand.
//
// r008 / I15 — "One route across Paris. Two ways to find it."
//
// Coordinates are SCREEN INTEGERS, already projected. See emit_ts.py for why
// this reel pre-projects where r006 did not. The stage constants are asserted
// against Astar.tsx at module load.
//
// Street data: (c) OpenStreetMap contributors, ODbL. The reel MUST show that
// credit on screen — a Produced Work may be distributed under any terms but
// the attribution is not optional.

/** Stage the coordinates were projected against. Astar.tsx asserts these. */
export const MAP_X = {MAP_X};
export const MAP_Y = {MAP_Y};
export const MAP_W = {MAP_W};
export const MAP_H = {MAP_H};

export const CITY = {json.dumps(CITY)};
export const FROM_NAME = "Arc de Triomphe";
export const TO_NAME = "Notre-Dame";

/** Every drivable street in the window, Douglas-Peucker simplified at 1.2 px. */
export const WAYS: number[][] = [
{chr(10).join("  " + arr(flat(w)) + "," for w in ways)}
];

/** Settle ORDER — the order each search committed to a junction. Flat [x,y,...]. */
export const DIJKSTRA: number[] = {arr(flat(DIJ))};
export const ASTAR: number[] = {arr(flat(AST))};
/** The route. Both searches returned this one, identically. */
export const PATH: number[] = {arr(flat(PATH))};

/** Junctions EXPANDED — the honest counters, before pixel-deduplication. */
export const DIJKSTRA_N = {len(dij["settled"])};
export const ASTAR_N = {len(ast["settled"])};
export const RATIO = {len(dij['settled']) / len(ast['settled']):.1f};
export const ROUTE_KM = {dij["cost"] / 1000:.1f};
export const JUNCTIONS = {len(pos)};
'''

OUT.write_text(ts)
print(f"""wrote {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)

  stage        {MAP_W} x {MAP_H} at ({MAP_X}, {MAP_Y})
  graph        {len(pos):,} junctions, {len(ways):,} drawn ways
  Dijkstra     {len(dij['settled']):,} expanded -> {len(DIJ):,} distinct pixels
  A*           {len(ast['settled']):,} expanded -> {len(AST):,} distinct pixels
  ratio        {len(dij['settled']) / len(ast['settled']):.1f}x
  route        {len(PATH)} points, {dij['cost']:,.0f} m — identical from both""")
