#!/usr/bin/env python3
"""Pack the I69 facts into a TS module -- and refuse to write if any is false.

Most of the angle table is NOT here: it is already baked into the Manim PNG
sequence. This module carries what the reel puts on screen in words, the
apparatus geometry (so labels drawn over the layer land ON the strings), the
camera (so the placement checks in check_annotations.py are checks on the
camera the reel actually uses), and the two angle columns the reel marks.
"""
import json
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'projects/r008_pendulum'))
D = json.loads((ROOT / 'projects/r008_pendulum/pendulum_data.json').read_text())

import camera  # noqa: E402
import layout as LO  # noqa: E402
import numpy as np  # noqa: E402

L, N, B = D['lengthsCm'], D['swingCounts'], D['beats']
G, TAU, C = 9.80665, D['tau'], D['nonlinearC']
COUNT = D['count']

# ── the claims the reel makes out loud ──────────────────────────────────────
assert COUNT == 15 == len(L) == len(N), 'not fifteen pendulums'
assert N == list(range(26, 41)), f'swing counts are not 26..40: {N[0]}..{N[-1]}'
assert TAU == 30.0, f'the cycle is not 30 s: {TAU}'
assert all(L[i] > L[i + 1] for i in range(COUNT - 1)), 'lengths not strictly decreasing'
assert 32.2 < L[0] < 32.5 and 13.5 < L[-1] < 13.8, f'lengths moved: {L[0]}, {L[-1]}'
assert D['finalErrorDeg'] < 0.02, f'the row does not reform: {D["finalErrorDeg"]}'
assert D['nonlinearC'] > 1.0, 'the nonlinear correction should lengthen the period'
assert abs(B['oneWave'] - TAU / (COUNT - 1)) < 0.01, 'the one-wave instant moved'
assert abs(B['reform'] - TAU) < 1e-9, f'the reform is not at {TAU} s'
assert D['runS'] > TAU, 'the run must continue past the reform so the reel can hold on it'

# The reel says the strings are VISIBLY different. 1.62x (the 60 s design) is
# not; that is the whole reason the cycle was shortened.
ratio = L[0] / L[-1]
assert ratio > 2.2, f'length ratio {ratio:.2f} -- too close to call them different'
assert (L[0] - L[1]) > 2.0, f'neighbours differ by only {L[0]-L[1]:.2f} cm at the long end'

# The reel PRINTS the design equation next to a length, so the equation has to
# be the one that actually produced it. The textbook form -- no C -- gives
# 33.07 cm where the string is 32.35 cm, and putting that on screen beside the
# labelled ropes would be a false claim of exactly the kind rule 7 exists for.
for i, n in enumerate(N):
    shown = G * (TAU / n) ** 2 / (4 * math.pi ** 2 * C ** 2) * 100.0
    assert abs(shown - L[i]) < 5e-3, \
        f'the on-screen equation gives {shown:.4f} cm for N={n}, string is {L[i]:.4f}'
naive = G * (TAU / N[0]) ** 2 / (4 * math.pi ** 2) * 100.0
assert naive - L[0] > 0.5, 'the C term is doing nothing; drop it from the frame'

# ── geometry, in the 1080x1920 reference px <ManimLayer> stretches across ────
P = LO.pivots()
assert len(P) == COUNT
assert abs(P[0][1] - 892.4) < 1.0 and abs(P[-1][0] - 789.2) < 1.0, \
    'the apparatus moved; re-render the Manim layer before shipping this'
U = (P[-1] - P[0]); U /= np.linalg.norm(U)
PERP = np.array([U[1], -U[0]])          # up-left, away from the hanging strings
pivots = [[round(float(x), 1), round(float(y), 1)] for x, y in P]

th = D['thetaCentiDeg']
assert len(th) == D['frames']
assert max(abs(v) for v in th[0]) <= D['theta0Deg'] * 100 + 1

cam_t = [k[0] for k in camera.KEYS]
assert cam_t == sorted(cam_t) and cam_t[0] == 0.0
assert cam_t[-1] == D['runS'], 'the camera does not cover the whole run'
# the payoff frame must not be caught mid-move
s_before, s_at = camera.cam(TAU - 0.4), camera.cam(TAU)
assert abs(s_before[0] - s_at[0]) < 1e-6 and abs(s_before[1] - s_at[1]) < 1e-6, \
    'the camera is still moving at the reform'
assert abs(s_at[0] - 1.0) < 1e-9, 'the reform is not framed at scale 1'

j = json.dumps
ts = f'''// GENERATED by projects/r008_pendulum/emit_ts.py -- do not edit.
// Every figure here was produced by integrating theta'' = -(g/L) sin(theta)
// in projects/r008_pendulum/simulate.py, and emit_ts.py refuses to write this
// file if any of them stops being true.

export const PENDULUM = {{
  count: {COUNT},
  fps: {D['fps']},
  frames: {D['frames']},
  /** Seconds simulated. Longer than the cycle: the reel holds past the reform. */
  runS: {D['runS']},
  /** The cycle. Every pendulum is back where it started at exactly this time. */
  tau: {TAU},
  reformFrame: {D['reformFrame']},
  theta0Deg: {D['theta0Deg']},
  /** Swings each pendulum completes in the {TAU:.0f} s cycle: {N[0]} through {N[-1]}. */
  swings: {j(N)},
  /** The same counts expressed per minute, which is how a person says them. */
  perMinute: {j(D['perMinute'])},
  /** String lengths in cm, solved against the EXACT nonlinear period. */
  lengthsCm: {j(L)},
  /** Each pendulum's own period in seconds -- tau/N by construction. */
  periodS: {j([round(v, 4) for v in D['periodS']])},
  /** T_true / T_smallangle at this amplitude. Not 1: the textbook is wrong here. */
  nonlinearC: {C},
  /** Standard gravity, CGPM 1901. The reel prints it. */
  g: {G},
  /** Worst bob's error from its release angle after a full cycle, in degrees. */
  reformErrorDeg: {D['finalErrorDeg']},
  beats: {{
    oneWave: {B['oneWave']},
    twoWave: {B['twoWave']},
    scramble: {B['scramble']},
    comb: {B['comb']},
    reform: {B['reform']},
  }},
  /**
   * Apparatus geometry in 1080x1920 reference px. <ManimLayer> stretches the
   * 1350x2400 render across exactly that box, so anything placed here inside
   * the camera div lands on the string Manim drew, at any camera scale.
   * From layout.py -- the same module the Manim scene lays itself out with.
   */
  pivots: {j(pivots)},
  rodPx: {j([round(float(LO.rod_px(i)), 1) for i in range(COUNT)])},
  bobPx: {j([round(float(LO.bob_px(i)), 1) for i in range(COUNT)])},
  /** Unit vector up-left of the beam: which way a length label sits. */
  perp: [{PERP[0]:.6f}, {PERP[1]:.6f}],
  /** Screen-space swing axis, y DOWN, unit. */
  swingAxis: [{LO.SWING[0]:.6f}, {LO.SWING[1]:.6f}],
  /** Angle of the longest and shortest bob, centi-degrees, one per frame. */
  thetaLongest: {j([r[0] for r in th])},
  thetaShortest: {j([r[COUNT - 1] for r in th])},
  /**
   * The camera, from camera.py. It lives there because that is where the
   * annotation placements are checked against it (check_annotations.py) --
   * a camera edited only here would invalidate those checks silently.
   */
  camera: {{
    t: {j([k[0] for k in camera.KEYS])},
    s: {j([k[1] for k in camera.KEYS])},
    x: {j([k[2] for k in camera.KEYS])},
    y: {j([k[3] for k in camera.KEYS])},
  }},
}} as const;
'''
out = ROOT / 'remotion/src/reels/data/pendulum.ts'
out.write_text(ts)
print(f'all claims hold: {COUNT} pendulums, {N[0]}..{N[-1]} swings in {TAU:.0f} s, '
      f'{L[0]:.2f}..{L[-1]:.2f} cm (ratio {ratio:.2f}x), '
      f'reform error {D["finalErrorDeg"]:.6f} deg, C = {C}')
print(f'on-screen equation reproduces all {COUNT} lengths '
      f'(textbook would say {naive:.2f} cm where the string is {L[0]:.2f} cm)')
print(f'camera: {len(camera.KEYS)} keys, locked at scale 1 from '
      f'{[k[0] for k in camera.KEYS if k[1] == 1.0 and k[0] < TAU][-1]:.1f}s through the reform')
print(f'wrote {out.relative_to(ROOT)}')
