#!/usr/bin/env python3
"""r012 / I84 -- pack income_data.json into a TS module, and REFUSE to write it
if any claim the reel makes on screen has stopped being true.

    python3 projects/r012_earnings/income.py && python3 projects/r012_earnings/emit_ts.py

Every assertion corresponds to words or a number in SCRIPT.md. This is the
mechanical half of non-negotiable 7 -- the beat times here MUST match the
constants at the top of remotion/src/reels/EarningsPeak.tsx, so a claim is
checked at the moment it is actually on screen, not just true somewhere in
the data (the r010 lesson: an approved script does not make a claim true).
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
D = json.loads((HERE / 'income_data.json').read_text())
AGES, VALUES = D['ages'], D['values']
META = D['meta']
checks = []


def claim(text, cond):
    assert cond, f'ON-SCREEN CLAIM IS FALSE: {text}'
    checks.append(text)


def income_at(age):
    """Nearest sampled value -- same lookup the .tsx does at playback."""
    i = min(range(len(AGES)), key=lambda k: abs(AGES[k] - age))
    return VALUES[i]


def dollars(v):
    return f'${round(v / 1000) * 1000:,.0f}'


# ── the reel's own timeline (screen seconds -> portrayed age), matching the
# AGE_KEYFRAMES constant in EarningsPeak.tsx exactly. ───────────────────────
AGE_KEYFRAMES = [
    (0.0, 22),
    (3.0, 30),
    (8.0, 40),
    (11.0, 46),   # reaches the peak
    (15.0, 46),   # held at the peak through here (4s hold, non-negotiable 5)
    (18.0, 55),   # crowd -> single-thread switch (cross-sectional -> panel-checked)
    (21.0, 61),
    (26.0, 98),   # beat 5: pulls back, reveal completes to the end of the real data
    (32.0, 98),   # beat 6: holds at the full curve
]

COPY_PEAK_LOCKS = 13.0     # "It's 46. $41,000. The peak." fully on screen
COPY_37K = 21.0            # "$37,000" reads on screen, at the end of beat 4


def age_at(t):
    for (t0, a0), (t1, a1) in zip(AGE_KEYFRAMES, AGE_KEYFRAMES[1:]):
        if t0 <= t <= t1:
            f = 0 if t1 == t0 else (t - t0) / (t1 - t0)
            return a0 + f * (a1 - a0)
    return AGE_KEYFRAMES[-1][1]


# ── claims, checked at the moment the copy makes them ───────────────────────
claim('at the moment the copy locks "$41,000. The peak.", the counter reads age 46',
      abs(age_at(COPY_PEAK_LOCKS) - 46) < 0.5)
claim('the value shown when the peak locks is $41,000',
      dollars(income_at(age_at(COPY_PEAK_LOCKS))) == '$41,000')
claim('at the moment "$37,000" reads, the counter has reached age 61',
      abs(age_at(COPY_37K) - 61) < 0.5)
claim('the value shown at that moment is $37,000',
      dollars(income_at(age_at(COPY_37K))) == '$37,000')
claim('46 is in fact the highest-income age in the whole sampled curve',
      max(range(len(AGES)), key=lambda k: VALUES[k]) == min(
          range(len(AGES)), key=lambda k: abs(AGES[k] - 46)))
claim('the crowd-to-thread visual switch (age 55) lands strictly after the peak (46)',
      age_at(18.0) > 46)
claim('the crowd-to-thread switch lands at or before the final counter value shown (61)',
      age_at(18.0) <= age_at(21.0))
claim('the source explicitly cross-checks 55-72 against real panel data, not a guess',
      55 in META['evidenceKind']['longitudinalCheck']
      and 72 in META['evidenceKind']['longitudinalCheck'])
claim('the peak age asserted on screen matches the source-derived meta',
      META['peakAge'] == 46 and META['peakValue'] == 41000)

TS = f"""// GENERATED by projects/r012_earnings/emit_ts.py -- do not hand-edit.
// Source: {META['source']}

export const PEAK_AGE = {META['peakAge']};
export const PEAK_VALUE = {META['peakValue']};
export const DROP_AT_61_PCT = {META['dropAt61Pct']};

export const AGE_KEYFRAMES: [number, number][] = {json.dumps(AGE_KEYFRAMES)};

export const CROSS_SECTIONAL_RANGE: [number, number] = {json.dumps(META['evidenceKind']['crossSectional'])};
export const LONGITUDINAL_CHECK_RANGE: [number, number] = {json.dumps(META['evidenceKind']['longitudinalCheck'])};

export const AGES: number[] = {json.dumps(AGES)};
export const VALUES: number[] = {json.dumps(VALUES)};
export const PCT_OF_PEAK: number[] = {json.dumps(D['pctOfPeak'])};

export const ANCHORS: {{ age: number; value: number }}[] = {json.dumps(D['anchors'])};
"""

out_dir = HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data'
out_dir.mkdir(parents=True, exist_ok=True)
out = out_dir / 'earningsPeak.ts'
out.write_text(TS)
print(f'wrote {out}\n')
for c in checks:
    print(f'  OK  {c}')
