/**
 * r015 · I77 -- GENERATED by projects/r015_moonmirrors/emit_ts.py. Do not hand-edit.
 *
 * There are mirrors on the Moon: Apollo 11, 14 and 15 (US, 1969-71) and the
 * Soviet Lunokhod 1 and 2 arrays (French-built, 1970/73) are all still in
 * use. An observatory fires a laser at one; by the time it arrives the beam
 * has spread to roughly 7 km wide, and of the
 * 3.1e+17 photons in a single APOLLO-station pulse, only
 * 5-10 are typically detected coming back. Timing that
 * round trip to a few picoseconds gives APOLLO's own stated ranging
 * precision of 1 mm on a 384,400 km distance -- and 57
 * years of that measurement show the Moon receding 3.83 cm every year.
 *
 * VERIFIED against APOLLO station instrument papers (Murphy et al.,
 * IOPscience), an LLR round-trip-loss review, and Eos.org's feature on the
 * current best-fit recession rate. Full table and sources: gate0/GATE0.md
 * Sec5. 19 on-screen claims are asserted by emit_ts.py, which
 * refuses to write this file if one of them stops being true.
 */

export const META = {
  earthMoonKm: 384400,
  oneWaySeconds: 1.2822203819416966,
  roundTripSeconds: 2.5644407638833933,
  photonsSent: 310000000000000000.0,
  photonsReturnedMin: 5,
  photonsReturnedMax: 10,
  photonsReturnedDisplay: 7,
  spotAtMoonKm: 7,
  spotAtEarthKm: 30,
  rangingPrecisionMm: 1,
  recessionCmYr: 3.83,
  firstYear: 1969,
  currentYear: 2026,
  yearsOfData: 57,
} as const;

/** [screenSeconds, realSeconds elapsed of THIS beam's round trip] -- the ONE ruler, beats 2-5. */
export const CLOCK_KEYFRAMES: [number, number][] = [
  [3.0, 0.0],
  [9.0, 1.2822203819416966],
  [14.0, 1.2822203819416966],
  [20.0, 2.5644407638833933],
  [26.0, 2.5644407638833933],
];

/** [screenSeconds, year] -- the time-lapse ruler, beat 6 only. */
export const YEAR_KEYFRAMES: [number, number][] = [
  [26.0, 1969],
  [30.0, 2026],
];

export const OBSERVATORY = { lon: -105.8, lat: 32.8 } as const;
export const REFLECTOR = { name: "APOLLO 15", year: 1971, lon: 3.6, lat: 26.1 } as const;

export type Mirror = { name: string; year: number; lon: number; lat: number };
export const MIRRORS: Mirror[] = [
  { name: "APOLLO 11", year: 1969, lon: 23.5, lat: 0.7 },
  { name: "APOLLO 14", year: 1971, lon: -17.5, lat: -3.6 },
  { name: "APOLLO 15", year: 1971, lon: 3.6, lat: 26.1 },
  { name: "LUNOKHOD 1", year: 1970, lon: -35.0, lat: 38.2 },
  { name: "LUNOKHOD 2", year: 1973, lon: 30.4, lat: 25.8 }
];
