// GENERATED by projects/r005_shuffle/emit_ts.py — do not edit by hand.
//
// Measured output of shuffle.py: 200,000 real Fisher-Yates shuffles of a
// 16-song playlist, 4 artists, 4 songs each.
//
// The self-check is a closed form. By linearity of expectation over the n-1
// adjacent slots, E[pairs] = sum_a k_a(k_a-1)/n = 3.0. The Monte
// Carlo lands at 3.0021. If those ever diverge, the shuffle is not uniform.
//
// NOT claimed anywhere in this reel: what any particular music company does with
// its shuffle. That could not be verified from here — see
// projects/r005_shuffle/NOTES.md for what was cut and how to reinstate it.

export const ARTISTS = 4;
export const PER_ARTIST = 4;
export const SONGS = 16;
export const TRIALS = 200000;

/** Percent of uniform shuffles with >= 2 songs by one artist adjacent. Base: 200,000 shuffles. */
export const PCT_CLUMPED = 96.45;
/** The complement — how often a shuffle comes out looking "properly shuffled". Same base. */
export const PCT_CLEAN = 3.55;
export const PCT_RUN_OF_3 = 31.12;
export const MEAN_PAIRS = 3.0021;
export const EXACT_PAIRS = 3.0;

/** Real shuffles, replayed frame for frame. Each entry is an artist index per slot. */
export const EXAMPLES: number[][] = [[3,2,2,3,2,1,3,2,3,0,0,0,0,1,1,1],[1,1,2,0,0,2,2,0,3,0,2,3,1,3,1,3],[1,1,0,0,3,2,0,2,3,1,2,0,2,1,3,3]];
export const EXAMPLE_PAIRS: number[] = [6,3,3];

/** Built to avoid repeats — 0 adjacent pairs, and far fewer permutations reachable. */
export const SPREAD: number[] = [1,0,2,3,1,2,0,3,0,1,3,2,3,2,1,0];

export const RUN_HIST: Record<string, number> = {"1":7106,"2":130644,"3":56607,"4":5643};
