"""Pack dct.py's measured run into a TS module the Remotion reel replays."""
import json

d = json.load(open('projects/r004_jpeg/jpeg_data.json'))
j = lambda o: json.dumps(o, separators=(',', ':'))
ex = d['example_block']
f = d['delta_to_final']
d['visually_done_n_3'] = next(i for i in range(1, 65) if f[i - 1] < 3.0)

out = f'''// GENERATED by projects/r004_jpeg/emit_ts.py — do not edit by hand.
//
// Every value here is measured output from dct.py, which builds the 64 DCT-II
// basis images from the cosine definition, transforms a real photograph block by
// block, quantises it with the table libjpeg ITSELF used (read back out of an
// encoded file rather than transcribed from Annex K), and reconstructs
// progressively while measuring the error at every coefficient count.
//
// The transform is proved the way qr_damage.py proves its mapping: keeping all
// 64 coefficients returns the original samples to {d['reconstruction_max_error']:.0e}.

export const SIZE = {d['size']};
export const BLOCKS = {d['blocks']};
/** Blocks across the frame. 16 is why the assembly is visible at all — see dct.py. */
export const BLOCKS_ACROSS = {d['size'] // 8};
export const QUALITY = {d['quality']};

/** Coefficient counts with a reconstruction PNG in public/reels. */
export const STOPS: number[] = {j(d['stops'])};

export type Step = {{ n: number; mae: number; psnr: number }};
/** Error at every coefficient count 1..64, measured on the real reconstruction. */
export const STEPS: Step[] = {j([{'n': s['n'], 'mae': s['mae'], 'psnr': s['psnr_db']} for s in d['steps']])};

/** The luminance quantisation table libjpeg used at quality {d['quality']}. */
export const QUANT: number[][] = {j(d['quant_table'])};

/**
 * One real 8x8 block — the busiest in the frame, so it is the HARDEST case for
 * the claim, not the easiest. A flat block would quantise to almost nothing and
 * prove the point too cheaply.
 */
export const EXAMPLE = {{
  index: {ex['index']},
  row: {ex['row']},
  col: {ex['col']},
  coefficients: {j(ex['coefficients'])} as number[][],
  quantised: {j(ex['quantised'])} as number[][],
  zeros: {ex['zeros_after_quantisation']},
}};

/**
 * Where the climb stops being worth watching. Measured against the FINAL
 * reconstruction, not the original: the question is when adding more stops
 * CHANGING anything. Below 3 of 255 at N={d['visually_done_n_3']}, below 2 at N={d['visually_done_n']}.
 */
export const DONE_N = {d['visually_done_n_3']};
export const DONE_DELTA = {d['delta_to_final'][d['visually_done_n_3'] - 1]};

/**
 * Colour. The SOURCE file is {d['colour']['source_sampling']}, so nothing here is claimed about it —
 * these are what libjpeg does at quality {d['quality']}, read back from a file it wrote.
 * Chroma is squashed by a factor and restored; the error is against the original.
 */
export const COLOUR = {{
  encoderSampling: {j(d['colour']['encoder_sampling'])},
  sourceSampling: {j(d['colour']['source_sampling'])},
  /** Squash factor -> mean abs RGB error of 255, COLOUR squashed. */
  chromaError: {j(d['colour']['chroma_error'])} as Record<string, number>,
  /** The same squash applied to BRIGHTNESS instead. */
  lumaError: {j(d['colour']['luma_error'])} as Record<string, number>,
}} as const;

export const STATS = {{
  coefficientsTotal: {d['coefficients_total']},
  quantisedNonzero: {d['quantised_nonzero']},
  /** Percent of ALL coefficients that quantise to zero. Base: {d['coefficients_total']} coefficients. */
  zeroPct: {d['quantised_zero_pct']},
  /** Mean non-zero coefficients per 8x8 block. Base: 64 slots per block. */
  meanKept: {d['mean_kept_per_block']},
}} as const;
'''

open('remotion/src/reels/data/jpeg.ts', 'w').write(out)
print('wrote remotion/src/reels/data/jpeg.ts')
