#!/usr/bin/env python3
"""Pack phantom_jam_data.json into a TS module, and REFUSE to write it if
anything the reel says on screen is not true of the data.

    python3 projects/r010_phantom_jam/emit_ts.py

This is the last gate before a number reaches a frame. Every check below is
something a viewer will actually read, or something the animation depends on.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'remotion' / 'src' / 'reels' / 'data' / 'phantomJam.ts'


MPS_5MPH = 5 / 2.236936


def stopped_share(frames):
    """Share of (car, frame) samples below 5 mph — the reel's definition of 'stopped'."""
    tot = sum(len(f['v']) for f in frames)
    return sum(1 for f in frames for a in f['v'] if a < MPS_5MPH) / tot


def checks(d):
    m, form, fix = d['meta'], d['form'], d['fix']
    jam_frames = [f for f in form if f['jam']]
    before = fix[:20]                       # first 10 s of the clip — still jammed
    after = fix[-40:]                       # last 20 s — the controller has settled
    sd = lambda fs: (sum((a - sum(b for f in fs for b in f['v']) / sum(len(f['v']) for f in fs)) ** 2
                         for f in fs for a in f['v']) / sum(len(f['v']) for f in fs)) ** 0.5
    return [
        ('"22 CARS" is what the frame says', m['nCars'] == 22),
        ('"755 FEET OF ROAD"', m['ringFt'] == 755),
        ('"ONE INSTRUCTION: 19 MPH"', m['targetMph'] == 19),
        ('the nudge is "FOUR INCHES"', m['nudgeInches'] == 4),
        ('the speed bar never has to show more than the ceiling', m['ceilingMph'] <= 25),
        ('a jam actually forms with no bottleneck',
         m['formedS'] < 120 and min(min(f['v']) for f in form[-20:]) < 2.0),
        ('the jam is a LOCALISED structure, not everyone slowing down',
         len(jam_frames) > len(form) * 0.5
         and all(f['jam'][1] < 0.30 * m['ringM'] for f in jam_frames)),
        ('the wave travels BACKWARDS', m['waveMps'] < 0),
        ('the cited 12 mph is honest against our own measurement',
         abs(m['waveMphSim'] - m['waveMphCited']) < 2.5),
        # ---- beat 6. The claim is NOBODY STOPS, not "the ring goes flat". -------
        ('cars really are stopping before the fix', stopped_share(before) > 0.08),
        ('"NOBODY STOPS ANY MORE" — zero cars under 5 mph once it settles',
         stopped_share(after) == 0.0),
        ('the speed variation is cut by at least 60%',
         sd(after) < 0.40 * sd(before)),
        ('the controlled car is one of the 22 on screen',
         0 <= m['controlCar'] < m['nCars']),
        ('every dumped frame has every car',
         all(len(f['x']) == m['nCars'] and len(f['v']) == m['nCars']
             for f in form + fix)),
    ]


def main():
    d = json.loads((HERE / 'phantom_jam_data.json').read_text())
    bad = [name for name, ok in checks(d) if not ok]
    for name, ok in checks(d):
        print(f"  {'ok  ' if ok else 'FAIL'} {name}")
    if bad:
        raise SystemExit(f"\nREFUSING TO WRITE — {len(bad)} claim(s) false:\n  " + "\n  ".join(bad))

    m = d['meta']
    print(f"\n  before fix: {100*stopped_share(d['fix'][:20]):5.1f}% of car-samples under 5 mph")
    print(f"  after fix:  {100*stopped_share(d['fix'][-40:]):5.1f}%")

    def frames(key):
        return ',\n'.join(
            '  { t: %s, x: [%s], v: [%s], jam: %s }' % (
                f['t'],
                ','.join(str(a) for a in f['x']),
                ','.join(str(a) for a in f['v']),
                'null' if f['jam'] is None else '[%s,%s]' % (f['jam'][0], f['jam'][1]),
            )
            for f in d[key]
        )

    ts = f'''/**
 * r010 · I65 — GENERATED by projects/r010_phantom_jam/emit_ts.py. Do not hand-edit.
 *
 * Optimal Velocity car-following (Bando et al. 1995) on the geometry of the real
 * experiment — 22 cars, 230 m ring, drivers told ~30 km/h and nothing else
 * (Sugiyama et al., New J. Phys. 10 (2008) 033001). The jam in `FORM` was not
 * authored: it condenses out of a 10 cm offset and nothing else.
 *
 * `FIX` is the same ring already jammed, with ONE car switching to FollowerStopper
 * (Stern et al., Transp. Res. C 89 (2018) 205-221) at t = 300 s.
 *
 * emit_ts.py asserts every claim the reel makes on screen and refuses to write
 * this file if one of them stops being true of the data.
 */

export type JamFrame = {{
  /** seconds of SIMULATION time since the start of this run */
  t: number;
  /** position of each car along the ring, metres */
  x: number[];
  /** speed of each car, m/s */
  v: number[];
  /** [centre, halfWidth] of the jam in metres, or null when nothing is jammed */
  jam: [number, number] | null;
}};

export const META = {{
  ringM: {m['ringM']},
  ringFt: {m['ringFt']},
  nCars: {m['nCars']},
  targetMps: {m['targetMps']},
  targetMph: {m['targetMph']},
  ceilingMph: {m['ceilingMph']},
  nudgeInches: {m['nudgeInches']},
  /** our own measurement, mph, magnitude */
  waveMphSim: {m['waveMphSim']},
  /** what goes ON SCREEN — Sugiyama et al. 2008, ~20 km/h. Cited, not ours. */
  waveMphCited: {m['waveMphCited']},
  crawlMph: {m['crawlMph']},
  /** Stern et al. 2018, fleet-wide, against the same cars with the wave running */
  fuelPct: {m['fuelPct']},
  formedS: {m['formedS']},
  controlCar: {m['controlCar']},
  /** seconds into the FIX clip at which that car changes behaviour */
  controlFromS: {m['controlFromS']},
  /** it targets 95% of uniform-flow speed — that is what opens the gap. GATE0 §5. */
  uFactor: {m['uFactor']},
  sampleS: {m['sampleS']},
}} as const;

/** 22 cars from a 10 cm offset, no control. The jam condenses. */
export const FORM: JamFrame[] = [
{frames('form')},
];

/** Already jammed, then one car stops closing its gap 10 s in. */
export const FIX: JamFrame[] = [
{frames('fix')},
];
'''
    OUT.write_text(ts, encoding='utf-8')
    print(f"\nwrote {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")
    print(f"  FORM {len(d['form'])} frames · FIX {len(d['fix'])} frames")


if __name__ == '__main__':
    main()
