#!/usr/bin/env python3
"""Pack stats.json + trace_data.json into remotion/src/reels/data/queue.ts.

This module REFUSES TO WRITE if the reel's claims are false. Every assertion
below is a sentence that appears on screen; if the simulation stops supporting
one, the build breaks here rather than shipping a lie (r001 shipped "the cafe
noise dies here" and it was false).

The one figure deliberately NOT exported is the maximum wait. It is the most
dramatic pair in the data — 53 min against 24 — and it swings by a factor of
two with the seed, so it cannot go on screen. See sim.py's seed sweep.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
S = json.loads((HERE / 'stats.json').read_text())
T = json.loads((HERE / 'trace_data.json').read_text())

one, four, oracle = S['modes']['shared'], S['modes']['visible'], S['modes']['oracle']

# ── the claims, in the order the reel makes them ───────────────────────────
assert abs(S['fastest_share'] - 0.25) < 0.005, \
    'ON SCREEN: "your line is the fastest of four, 25% of the time"'

assert T['roundsYours'] <= T['roundsN'], 'the tally cannot exceed the rounds shown'

assert not T['big'][str(T['you'])], \
    'ON SCREEN: the shopper we follow carries a BASKET — the wait is not theirs'
assert T['youWait4'] > T['youWait1'] * 3, \
    'ON SCREEN: the same shopper, same basket, waits far longer in four lines'

thru_gap = abs(four['thru'] - one['thru']) / one['thru']
assert thru_gap < 0.001, \
    f'ON SCREEN: "same 204 served an hour" — gap is {thru_gap:.4%}'

assert abs(oracle['mean'] - one['mean']) < 0.005, \
    'ON SCREEN: "with x-ray vision, four lines tie one line exactly"'

cut_mean = 1 - one['mean'] / four['mean']
cut_p95 = 1 - one['p95'] / four['p95']
assert 0.14 < cut_mean < 0.18, f'ON SCREEN: "16% off the average" — got {cut_mean:.1%}'
assert 0.21 < cut_p95 < 0.26, f'ON SCREEN: "a quarter off the bad day" — got {cut_p95:.1%}'

assert S['sweep']['p95']['hi'] - S['sweep']['p95']['lo'] < 0.05, \
    'the p95 ratio must be seed-stable before it goes on screen'
assert S['sweep']['mx']['hi'] - S['sweep']['mx']['lo'] > 0.2, \
    'the maximum is supposed to be the unstable one — recheck if this fails'

# "Same shoppers, same baskets" is a claim about the INPUT, which is identical by
# construction. The displayed sets are not equal and must not be asserted equal:
# the window opens with the four-line shop still holding people the one-line shop
# has already released. That asymmetry only ever runs one way.
ids4 = {e[0] for f in T['four'] for e in f}
ids1 = {e[0] for f in T['one'] for e in f}
assert ids1 <= ids4, \
    'the FASTER shop cannot hold a shopper the slower one has already released'
assert all(i in ids4 and i in ids1 for i in T['arrivedInWindow']), \
    'ON SCREEN: "same shoppers" — everyone arriving in the window must be in both'
assert all(T['four'][f] and T['one'][f] for f in range(T['raceFrames'])), \
    'a shop goes empty mid-race'

print(f'all claims hold: {len(ids4)}/{len(ids1)} shoppers on screen, '
      f'{T["raceFrames"]} race frames, '
      f'mean cut {cut_mean:.1%}, p95 cut {cut_p95:.1%}, throughput gap {thru_gap:.4%}')


def pack(frames):
    """[[id,x,y,state], ...] per frame -> flat CSV-ish rows, 3dp."""
    return '[' + ','.join(
        '[' + ','.join(f'[{e[0]},{e[1]:.3f},{e[2]:.3f},{e[3]}]' for e in f) + ']'
        for f in frames) + ']'


out = Path(HERE.parent.parent / 'remotion/src/reels/data/queue.ts')
out.write_text(f'''/**
 * GENERATED by projects/i64_queue/emit_ts.py — do not hand-edit.
 *
 * Two sources, both real runs:
 *   sim.py    {S['n']:,} shoppers, {S['c']} tills at {S['rho']:.0%} — every FIGURE on screen
 *   trace.py  a {T['t1'] - T['t0']:.1f}-minute EXCERPT of a long run — every POSITION on screen
 *
 * Positions are panel-local floats: x=1 is the till column, y=0..1 spans the
 * four lanes. Queue logic, the walk to the till and the exit are all resolved in
 * Python, so the .tsx cannot disagree with the simulation.
 *
 * state: 0 waiting or walking, 1 being served, 2 leaving
 */

/** Waits in minutes. One time unit = one minute: baskets average
 *  {S['small'] * 60:.0f}s, trolleys {S['big']:.0f} min, mixture mean 1 min. */
export const STATS = {{
  tills: {S['c']},
  utilisation: {S['rho']},
  shoppers: {S['n']},
  oneMean: {one['mean']:.3f},
  onePct95: {one['p95']:.3f},
  fourMean: {four['mean']:.3f},
  fourPct95: {four['p95']:.3f},
  oracleMean: {oracle['mean']:.3f},
  oneThroughput: {one['thru']:.2f},
  fourThroughput: {four['thru']:.2f},
  cutMean: {cut_mean:.4f},
  cutPct95: {cut_p95:.4f},
  fastestShare: {S['fastest_share']:.4f},
}} as const;

/** The shopper the reel follows, in both shops. Chosen by a rule fixed before
 *  the run — see trace.py. Basket of {T['youBasket'] * 60:.0f} seconds. */
export const YOU = {{
  id: {T['you']},
  wait4: {T['youWait4']:.2f},
  wait1: {T['youWait1']:.2f},
  basketSeconds: {T['youBasket'] * 60:.0f},
}} as const;

export const RACE_FRAMES = {T['raceFrames']};
export const SIM_MINUTES = {T['t1'] - T['t0']:.2f};
export const TROLLEY: ReadonlySet<number> = new Set({sorted(int(k) for k, v in T['big'].items() if v)});

/** Beat 3: {T['roundsN']} rounds of "which of four lanes frees first".
 *  `yours` is the tally of the rounds actually shown, not the long-run share. */
export const ROUNDS: readonly {{ win: number; fill: readonly number[] }}[] = {
    json.dumps([dict(win=r['win'], fill=[round(f, 4) for f in r['fill']])
                for r in T['rounds']])};
export const ROUNDS_YOURS = {T['roundsYours']};

export type Body = readonly [id: number, x: number, y: number, state: number];

export const FOUR: readonly (readonly Body[])[] = {pack(T['four'])};

export const ONE: readonly (readonly Body[])[] = {pack(T['one'])};
''')
print(f'wrote {out}  ({out.stat().st_size/1024:.0f} KB)')
